config/routes.rb
Rails.application.routes.draw do
  devise_for :couples, controllers: { registrations: "registrations" }

  get 'couples/:id/edit-profile' => 'couples#edit', as: :my_profile
  patch  'couples/:id', to: 'couples#update'
  get    "couples/:id",      to: "couples#show", as: :couple_profile

  root to: 'pages#home'

  get 'challenges', to: 'pages#challenges'

    resources :couples do
        get 'my_events', to: 'events#my_events'
      resources :events do
        resources :swipes
        post 'swipeleft', to: 'swipes#guest_swipe_left'
        post 'swiperight', to: 'swipes#guest_swipe_right'
      end
    end

    resources :events do
      resources :couples do
        post 'swipeleft', to: 'swipes#organiser_swipe_left'
        post 'swiperight', to: 'swipes#organiser_swipe_right'
      end
    end

  namespace :organiser do
    resources :events do
      resources :couples
    end
  end

  resources :messages, only: [:new, :create, :destroy]

  resources :events do
    patch :notification_false
  end

  mount Attachinary::Engine => "/attachinary"

end

app/views/shared/_flashes.html.erb
<% if notice %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= notice %>
    </div>
  <% end %>
<% if alert %>
    <div class="alert alert-info alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= alert %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagonnav-fixed navbar-<%= controller.controller_name %> navbar-<%= controller.controller_name %>-<%= action_name %>">
  <!-- Logo -->
  <% if controller.controller_name == "sessions" || controller.controller_name == "registrations" || controller.controller_name == "passwords" || controller.controller_name == "events" && action_name == "edit" || controller.controller_name == "events" && action_name == "new" %>
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "fraise_rose_navbar.png" %>
    <% end %>
  <% elsif action_name == "home" %>
    <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "fraise-blanc.png" %>
    <% end %>
  <% else %>
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "fraise-fond-rose.png" %>
    <% end %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm title-spacing">


    <!-- Different navigation if login or not -->
    <% if couple_signed_in? %>

      <!-- Challenges -->
      <%= link_to t(".sign_in", default: "CHALLENGES"), challenges_path, class: "navbar-item navbar-wagon-link" %>

      <!-- Create an event -->
      <%= link_to t(".sign_in", default: "ORGANISER"), new_organiser_event_path, class: "navbar-item navbar-wagon-link" %>

      <!-- Swipe events -->
      <%= link_to t(".sign_in", default: "PARTICIPER"), events_path, class: "navbar-item navbar-wagon-link" %>

      <% count = 0 %>
      <% swipes_true = Swipe.where(couple_id: current_couple, notification_couple: true) %>
      <% swipes_related_event = current_couple.event_swipes.where(notification_event: true) %>
      <% swipes_true.each do |st| %>
        <% count += 1 %>
      <% end %>
      <% swipes_related_event.each do |st| %>
        <% count += 1 %>
      <% end %>

      <% if count >= 1 %>
        <%= link_to t(".sign_in", default: "EVENEMENTS (#{count})"),
        couple_my_events_path(current_couple), class: "navbar-item navbar-wagon-link event-alert" %>
      <% else %>
        <%= link_to t(".sign_in", default: "EVENEMENTS"),
          couple_my_events_path(current_couple), class: "navbar-item navbar-wagon-link" %>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-item">
        <div class="dropdown">
          <%= cl_image_tag current_couple.profile_pict, :height=>875, :width=>875, :crop=>"crop", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to couple_profile_path(current_couple) do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "NOTRE PROFIL") %>
              <% end %>
            </li>
            <li>
              <%= link_to root_path do %>
                <i class="fa fa-home"></i>  <%= t(".profile", default: "HOME") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_couple_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "SE DÉCONNECTER") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>


    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "SE CONNECTER"), new_couple_session_path, class: "navbar-item navbar-wagon-link" %>

    <% end %>

  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle pink-hamburger" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if couple_signed_in? %>
          <li>
            <%= link_to couple_profile_path(current_couple) do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "NOTRE PROFIL") %>
            <% end %>
          </li>
          <li>
            <%= link_to root_path do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "HOME") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_couple_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "SE DÉCONNECTER") %>
            <% end %>
          </li>
         <% else %>
           <!-- Login text link -->
           <%= link_to t(".sign_in", default: "SE CONNECTER"), new_couple_session_path, class: "navbar-item navbar-wagon-link" %>
        <% end %>
      </ul>
    </div>
  </div>
</div>