config/routes.rb
Rails.application.routes.draw do
  devise_for :couples, controllers: { registrations: "registrations" }

  get 'couples/:id/edit-profile' => 'couples#edit', as: :my_profile
  patch  'couples/:id', to: 'couples#update'
  get    "couples/:id",      to: "couples#show", as: :couple_profile

  root to: 'pages#home'

  get 'challenges', to: 'pages#challenges'

    resources :couples do
        get 'my_events', to: 'events#my_events'
      resources :events do
        resources :swipes
        post 'swipeleft', to: 'swipes#guest_swipe_left'
        post 'swiperight', to: 'swipes#guest_swipe_right'
      end
    end

    resources :events do
      resources :couples do
        post 'swipeleft', to: 'swipes#organiser_swipe_left'
        post 'swiperight', to: 'swipes#organiser_swipe_right'
      end
    end

  namespace :organiser do
    resources :events do
      resources :couples
    end
  end

  resources :messages, only: [:new, :create, :destroy]

  resources :events do
    patch :notification_false
  end

  mount Attachinary::Engine => "/attachinary"

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :couple
  belongs_to :theme
  has_many :swipes
  has_many :messages

  after_create :add_master_badge



  def add_master_badge
    if couple.events.count == 5
      couple.badges << Badge.find_by(name: "Maitresse de Maison")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    available_event_list
  end

  def my_events
    @my_events = Event.where(couple: current_couple).order(date: :desc)
    @participating_events = Event.joins(:swipes).where(swipes: { couple_id: current_couple.id, participation: true })
    @swipes_true = Swipe.where(event_id: params[:id], participation: true)
  end

  def notification_false
    the_event = Event.find_by(id: params[:event_id])
    if current_couple == the_event.couple
      swipes_true = Swipe.where(event_id: the_event, participation: true)
      swipes_true.each do |st|
        st.notification_event = false
        st.save
      end
    else
      swipe_participating_couple = Swipe.where(event_id: the_event, couple_id: current_couple, participation: true).first
      swipe_participating_couple.notification_couple = false
      swipe_participating_couple.save
    end

    redirect_to event_path(the_event)
  end

  def new
    @event = current_couple.events.new
  end

  def create
    @event = current_couple.events.new(event_params)
    if @event.save
       current_couple.fraises += 3
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
  end

  def show
    @event = Event.find_by(id: params[:id])
    @message = Message.new()
    @swipes_true = Swipe.where(event_id: params[:id], participation: true)
  end


  def available_event_list
    swipe_event_ids = Swipe.where(couple: current_couple, guest_couple_swipe: true).pluck(:event_id).uniq
    @events_for_display = Event.where.not(id: swipe_event_ids, couple: current_couple).where("date > ?", Date.today)
 end




end

app/controllers/organiser/events_controller.rb
class Organiser::EventsController < ApplicationController


  def index
    @events = current_couple.events

  end

  def new
    @event = current_couple.events.new
  end

  def edit
    @event =current_couple.events.find(params[:id])
  end

  def show
    @event =current_couple.events.find(params[:id])
  end

  def create
    @event = current_couple.events.new(event_params)
    if @event.save
      current_couple.fraises += 5
      current_couple.save
      redirect_to couple_event_path(current_couple, @event)
    else
      render 'new'
    end
  end

  def destroy
    @event = current_couple.events.find(params[:id])
    @event.destroy
    redirect_to organiser_events_path
  end


  def update
    @event = current_couple.events.find(params[:id])

    if @event.update(event_params)
      flash[:notice] = 'Your event was updated succesfully'
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  private

  def event_params
    params.require(:event).permit(:date, :description, :city,:max_n_guest_couples,:theme_id)
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="container-fluid swipe-container">
  <div class="row row-interline">
    <div class="col-xs-6 top-row-swipe-block swipe-no"></div>
    <div class="col-xs-6 top-row-swipe-block swipe-yes"></div>
  </div>

  <div class="row main-swipe-row">
    <div class="col-xs-2 col-sm-3 col-md-4 swipe-block swipe-no">
      <div class="hidden-xs">
        <h2>BOF PAS <br> A MON <br> GOUT...</h2>
        <%= image_tag 'patate_grise.png', size: "105x70" %>
      </div>
    </div>
    <div class="col-xs-8 col-sm-6 col-md-4 event-background" id="event-deck" >
      <%= render 'swipes/event_deck', events_for_display: @events_for_display %>
    </div>
    <div class="col-xs-2 col-sm-3 col-md-4 swipe-block swipe-yes">
      <div class="hidden-xs">
        <h2>HUM CA <br> SENT LA <br> FRAISE !</h2>
        <%= image_tag 'fraise_large.png', size: "70x105" %>
      </div>
    </div>
  </div>

</div>






  <%= content_for(:after_js) do %>
      <script>

      $('#current-active-card').flip();


        function moveLeft() {
          var elem = document.getElementById("current-active-card");
          var pos = 0;
          var id = setInterval(frame, 1);
          function frame() {
              if (pos == 400) {
                clearInterval(id);
              } else {
                pos++;
                elem.style.right = 6*pos + 'px';
              }
            }
          }

        function moveRight() {
          var elem = document.getElementById("current-active-card");
          var pos = 0;
          var id = setInterval(frame, 1);
          function frame() {
              if (pos == 400) {
                clearInterval(id);
              } else {
                pos++;
                elem.style.left = 6*pos + 'px';
              }
            }
          }


        function coupleSwipeLeft(){
            $('.active-card').hide();

            var event_id = $('.active-card').attr("data-id");

             $.ajax({
                url:  "/couples/"+ '<%= current_couple.id %>' +"/events/"+ event_id +"/swipeleft",
                type: 'POST',
                dataType: "json",
              });
            location.reload();
        }

        function coupleSwipeRight() {
          $('.active-card').hide();

          var event_id = $('.active-card').attr("data-id");

          $.post( "/couples/"+ '<%= current_couple.id %>' +"/events/"+ event_id +"/swiperight", function( data ) {
              if (data["current_swipe"]["participation"] == true) {
                swal({title: "Chic ! Ca matche !",
                      text: "Vous vous plaisez dis donc ! L’événement vient d'être ajouté à votre liste, échangez entre vous et regardez qui participera",
                      closeOnConfirm: false,
                      confirmButtonColor: "#F80C54",
                      imageUrl: "<%= asset_path("fraise-kawai.png")%>",
                      imageSize: "120x120",
                    }, function(isConfirm){
                      if (isConfirm) { location.reload(); }
                    });
              }
              else {
                location.reload();
              }
            });

        }

        $(document).ready(function(){
          $('.couple-swipe-left-btn').on('click', function() {
            moveLeft();
            setTimeout(function(){
              coupleSwipeLeft();
            }, 150);
          });
          $('.couple-swipe-right-btn').on('click', function() {
            moveRight();
            setTimeout(function(){
              coupleSwipeRight();
            }, 150);
          });

          $(document).on('keyup', function(event) {
            if (event.keyCode == 37) {
              moveLeft();
              setTimeout(function(){
                coupleSwipeLeft();
              }, 150);
            } else if (event.keyCode == 39) {
              moveRight();
              setTimeout(function(){
              coupleSwipeRight();
            }, 150);
            }
          });


          $('.active-card').draggable({ axis: "x",
          zIndex: 2500 });
          $('.swipe-no').droppable({
            drop: function(event, ui) {
              coupleSwipeLeft();
            }
          });
          $('.swipe-yes').droppable({
            drop: function(event, ui) {
              coupleSwipeRight();
            }
          });
        });
      </script>
    <% end %>

app/views/events/my_events.html.erb
  <div class="container">

    <h1 class="text-center title-spacing form-title-my-events">MES EVENEMENTS</h1>


    <div class="line-separation">

    </div>

    <% count = 0 %>
    <% swipes_related_event = current_couple.event_swipes.where(notification_event: true) %>
    <% swipes_related_event.each do |st| %>
      <% count += 1 %>
    <% end %>

    <% count_participate = 0 %>
    <% swipes_true = Swipe.where(couple_id: current_couple, notification_couple: true) %>
    <% swipes_true.each do |st| %>
      <% count_participate += 1 %>
    <% end %>




    <ul id=myTabs class="nav nav-tabs tabs">
      <% if count >= 1 %>
        <li role="presentation" class="tab active form-title-h2-events"><h2><%= link_to "J'ORGANISE (#{count})", "#organize", aria: { controls: 'organize'}, role: "tab", data: {toggle: "tab"} %></h2></li>
      <% else %>
        <li role="presentation" class="tab active title-spacing"><h2><%= link_to "J'ORGANISE", "#organize", aria: { controls: 'organize'}, role: "tab", data: {toggle: "tab"} %></h2></li>
      <% end %>

      <% if count_participate >= 1 %>
        <li role="presentation" class="tab form-title-h2-events"><h2><%= link_to "JE PARTICIPE (#{count_participate})", "#participate",  aria: { controls: 'participate'}, role: "tab", data: {toggle: "tab"}  %></h2></li>
      <% else %>
        <li role="presentation" class="tab title-spacing"><h2><%= link_to "JE PARTICIPE", "#participate",  aria: { controls: 'participate'}, role: "tab", data: {toggle: "tab"}  %></h2></li>
      <% end %>
    </ul>

    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="organize">
        <% count = 0 %>
        <% swipes_related_event = current_couple.event_swipes.where(notification_event: true) %>
        <% swipes_related_event.each do |st| %>
          <% count += 1 %>
        <% end %>

        <div class="row">
          <div class="line-separation">
            <h3> A venir</h3>
          </div>
          <% @my_events.each do |event| %>
          <% next if event.date < Time.now %>

            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="card-events">
                <div class="text-center">
                  <% if Swipe.find_by(event_id: event.id) %>
                    <% if current_couple == event.couple &&  Swipe.find_by(event_id: event.id, notification_event: true ) %>
                      <p class="card-notification"><span class="label label-new">NEW</span></p>
                    <% end %>
                  <% end %>



                  <%= cl_image_tag event.couple.profile_pict, height: 100, width: 100, crop: :fill, class:"img-circle" %>
                  <h5><%= l(event.date, format: :short) %></h5>
                  <h4><strong>Organisateurs de l'événement</strong></h4>
                    <% if event.couple_id = current_couple.id %>
                  <p>Vous<p>
                    <% else %>
                  <p><%= Couple.find_by(id: event.couple_id).couple_nickname %><p>
                    <% end %>
                  <h4><strong>Thème de l'événement</strong></h4>
                  <p><%= Theme.find_by(id: event.theme_id).name %></p>

                  <%= link_to "Communiquer", event_notification_false_path(event), class: "btn btn-default btn-nice", method: :patch %>
                </div>
              </div>
            </div>
          <% end %>
        </div>


        <div class="row">
          <div class="line-separation">
            <h3> Passés</h3>
          </div>
          <% @my_events.each do |event| %>
          <% next if event.date > Time.now %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="card-events">
                <div class="text-center">
                <% if Swipe.find_by(event_id: event.id) %>
                  <% if current_couple == event.couple &&  Swipe.find_by(event_id: event.id, notification_event: true) %>
                    <p class="card-notification"><span class="label label-new">NEW</span></p>
                  <% end %>
                <% end %>

                  <%= cl_image_tag event.couple.profile_pict, height: 100, width: 100, crop: :fill, class:"img-circle" %>
                  <h5><%= l(event.date, format: :short) %></h5>
                  <h4><strong>Organisateurs de l'événement</strong></h4>
                    <% if event.couple_id = current_couple.id %>
                  <p>Vous<p>
                    <% else %>
                  <p><%= Couple.find_by(id: event.couple_id).couple_nickname %><p>
                    <% end %>
                  <h4><strong>Thème de l'événement</strong></h4>
                  <p><%= Theme.find_by(id: event.theme_id).name %></p>
                  <%= link_to "Communiquer", event_notification_false_path(event), class: "form-submit-btn", method: :patch %>
                </div>
              </div>
            </div>
          <% end %>

        </div>
      </div>

      <div role="tabpanel" class="tab-pane" id="participate">


        <div class="row">

          <div class="line-separation">
            <h3 class="form-title-h3-events"> EVENEMENTS A VENIR</h3>
          </div>
          <% @participating_events.each do |event| %>
          <% next if event.date < Time.now %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="card-events">
                <div class="text-center">
                <% if Swipe.find_by(event_id: event.id) %>
                  <% if Swipe.find_by(event_id: event.id, notification_couple: true) %>
                    <p class="card-notification"><span class="label label-new">NEW</span></p>
                  <% end %>
                <% end %>

                  <%= cl_image_tag event.couple.profile_pict, height: 100, width: 100, crop: :fill, class:"img-circle" %>
                  <h5><%= l(event.date, format: :short) %></h5>
                  <h4><strong>Organisateurs de l'événement</strong></h4>
                    <% if event.couple_id = current_couple.id %>
                  <p>Vous<p>
                    <% else %>
                  <p><%= Couple.find_by(id: event.couple_id).couple_nickname %><p>
                    <% end %>              <h4><strong>Thème de l'événement</strong></h4>
                  <p><%= Theme.find_by(id: event.theme_id).name %></p>


                  <%= link_to "Communiquer", event_notification_false_path(event), class: "btn btn-default btn-nice", method: :patch %>
                </div>
              </div>
            </div>
          <% end %>

        </div>


        <div class="row">
          <div class="line-separation">
            <h3 class="form-title-h3-events"> EVENEMENTS PASSES</h3>
          </div>
          <% @participating_events.each do |event| %>
          <% next if event.date > Time.now %>
            <div class="col-xs-12 col-sm-6 col-md-4">
              <div class="card-events">
                <div class="text-center">
                <% if Swipe.find_by(event_id: event.id) %>
                  <% if Swipe.find_by(event_id: event.id, notification_couple: true) %>
                    <p class="card-notification"><span class="label label-new">NEW</span></p>
                  <% end %>
                <% end %>

                  <%= cl_image_tag event.couple.profile_pict, height: 100, width: 100, crop: :fill, class:"img-circle" %>
                  <h5><%= l(event.date, format: :short) %></h5>
                  <h4><strong>Organisateurs de l'événement</strong></h4>
                    <% if event.couple_id = current_couple.id %>
                  <p>Vous<p>
                    <% else %>
                  <p><%= Couple.find_by(id: event.couple_id).couple_nickname %><p>
                    <% end %>              <h4><strong>Thème de l'événement</strong></h4>
                  <p><%= Theme.find_by(id: event.theme_id).name %></p>


                  <%= link_to "Communiquer", event_notification_false_path(event), class: "btn btn-default btn-nice", method: :patch %>
                </div>
              </div>
            </div>
          <% end %>

        </div>
      </div>
    </div>

  </div>

app/views/events/new.html.erb
<div class="container">
   <div class="row">
     <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for(@event) do |f| %>
        <%= f.input :date, label: "A quelle date souhaitez-vous creer votre evenement ?" %>
        <%= f.input :max_n_guest_couples, label: "Quel est le nombre de couples participants maximum?" %>
        <%= f.input :description, label: "Merci de detailler votre evenement" %>
        <%= f.input :city, label: "Ou se tiendra votre evenement ?" %>
        <%= f.button :submit %>
      <% end %>
   </div>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">

  <div class="container-show-event">

    <div class="row">
      <div class="col-xs-12">
        <div class="card-event-profile text-center no-text-decoration">
          <%= cl_image_tag @event.couple.profile_pict, height: 200, crop: :fill, class:"avatar-event-profile img-thumbnail" %>

          <h3 class="title-spacing"><%= @event.theme.name.upcase %> CHEZ <%= @event.couple.couple_nickname.upcase %></h3>
          <h5>Description</h5>
          <h4><%= @event.description %></h4>
          <h5>Couple organisateur</h5>
          <h4><%= link_to "#{@event.couple.couple_nickname}: #{@event.couple.member1_name} & #{@event.couple.member2_name}", couple_path(@event.couple) %></h4>
          <h5>Date</h5>
          <h4><%= l(@event.date, format: :default) %></h4>
          <h5>Couples participants</h5>
          <% @swipes_true.each do |st| %>
          <h4><%= link_to "#{Couple.find_by(id: st.couple_id).couple_nickname}: #{Couple.find_by(id: st.couple_id).member1_name} & #{Couple.find_by(id: st.couple_id).member2_name}", couple_path(st.couple_id) %></h4>
          <% end %>


            <div class="update-event-show">
              <% if current_couple.id == @event.couple_id %>
                <%= link_to "TROUVER DES PARTICIPANTS", organiser_event_couples_path(@event) %>
                <%= link_to "METTRE A JOUR L'EVENEMENT", edit_organiser_event_path(@event) %>
              <% end %>
            </div>
          </div>
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12">

        <div class="card-event-profile">

          <div class="form-inbox">

            <%= simple_form_for @message, url: messages_path, method: :post do |f| %>
              <%= f.error_notification %>
              <%= f.hidden_field :couple_id,:value => current_couple.id %>
              <%= f.hidden_field :event_id,:value => @event.id %>
              <%= f.hidden_field :date,:value => Time.now %>
              <%= f.input :content, label: false, placeholder: "Votre message...", input_html: {class: "form-message-background"} %>
              <%= f.button :submit, "Envoyer", class: "btn-inbox btn-custom form-submit-btn"  %>
            <% end %>

          </div>


          <div>
            <% @event.messages.order(date: :desc).each do |message| %>
              <% if message.couple == current_couple %>
                <div class="message-current-user">
                  <%= cl_image_tag message.couple.profile_pict, height: 200, width: 200, crop: :fill, class:"avatar-chat" %>
                  <h4><strong>Vous</strong></h4>
                  <h4><%= message.content %> </h4>
                  <p><em><%= l(message.date, format: :short) %></em></p>
                </div>
              <% else %>

                <div class="message-other-user">
                  <%= cl_image_tag message.couple.profile_pict, height: 200, width: 200, crop: :fill, class:"avatar-chat" %>
                  <h4><strong><%= message.couple.couple_nickname %></strong></h4>
                  <h4><%= message.content %> </h4>
                  <p><em><%= l(message.date, format: :short) %></em></p>
                </div>
              <%end %>
            <% end %>
          </div>


        </div>
      </div>
    </div>

  </div>
</div>