config/routes.rb
Rails.application.routes.draw do
  devise_for :couples, controllers: { registrations: "registrations" }

  get 'couples/:id/edit-profile' => 'couples#edit', as: :my_profile
  patch  'couples/:id', to: 'couples#update'
  get    "couples/:id",      to: "couples#show", as: :couple_profile

  root to: 'pages#home'

  get 'challenges', to: 'pages#challenges'

    resources :couples do
        get 'my_events', to: 'events#my_events'
      resources :events do
        resources :swipes
        post 'swipeleft', to: 'swipes#guest_swipe_left'
        post 'swiperight', to: 'swipes#guest_swipe_right'
      end
    end

    resources :events do
      resources :couples do
        post 'swipeleft', to: 'swipes#organiser_swipe_left'
        post 'swiperight', to: 'swipes#organiser_swipe_right'
      end
    end

  namespace :organiser do
    resources :events do
      resources :couples
    end
  end

  resources :messages, only: [:new, :create, :destroy]

  resources :events do
    patch :notification_false
  end

  mount Attachinary::Engine => "/attachinary"

end

app/models/swipe.rb
class Swipe < ActiveRecord::Base
  belongs_to :event
  belongs_to :couple

  after_create :add_epicure_badge, :add_hungry_badge


  def add_epicure_badge
    if couple.swipes.count == 50
      couple.badges << Badge.find_by(name: "Touche a tout")
    end
  end

  def add_hungry_badge
    if couple.swipes.where("organizing_couple_swipe_result IS TRUE OR guest_couple_swipe_result IS TRUE").count >= 20
        couple.badges << Badge.find_by(name: "Gourmand")
    end
  end

end

app/controllers/swipes_controller.rb
class SwipesController < ApplicationController



  def create
  end


  def update
  end

  def set_swipe
    @event = Event.find(params[:event_id])
    @organiser_couple = @event.couple
    @participating_couple = Couple.find(params[:couple_id])
    Swipe.new(couple: @participating_couple, event: @event)
  end

  def swipe_exists?(tested_swipe)
    @event_swipes = Swipe.all.where(event: tested_swipe.event)
    @event_couple_swipe = @event_swipes.select { |swipe| swipe.couple == tested_swipe.couple}

    if @event_couple_swipe.length == 0
      tested_swipe
    else
      @event_couple_swipe[0]
    end

  end

  def organiser_swipe_right

    set_swipe
    respond_to do  |format|
      @current_swipe = swipe_exists?(set_swipe)
      @current_swipe.organizing_couple_swipe = true
      @current_swipe.organizing_couple_swipe_result = true
      @current_swipe.save
      # on check sil y a match
      check_match(@current_swipe)
      swipe_couple_ids = Swipe.where(event: @event, organizing_couple_swipe: true).pluck(:couple_id)
      @couples_for_display = Couple.where.not(id: swipe_couple_ids).where.not(id: current_couple.id)
      if @current_swipe.match
        check_participation(@current_swipe)
      end
      format.json {
        render json: { current_swipe: @current_swipe, couples: @couples_for_display}
      }
    end
  end

  def organiser_swipe_left
     set_swipe
    respond_to do  |format|
      @current_swipe = swipe_exists?(set_swipe)
      @current_swipe.organizing_couple_swipe = true
      @current_swipe.organizing_couple_swipe_result = false
      @current_swipe.save
      # on check sil y a match
      check_match(@current_swipe)
      swipe_couple_ids = Swipe.where(event: @event, organizing_couple_swipe: true).pluck(:couple_id)
      @couples_for_display = Couple.where.not(id: swipe_couple_ids).where.not(id: current_couple.id)
      format.json {
        render json: { current_swipe: @current_swipe, couples: @couples_for_display}
      }
    end
  end

  def guest_swipe_right
    set_swipe
    respond_to do  |format|
      @current_swipe = swipe_exists?(set_swipe)
      @current_swipe.guest_couple_swipe = true
      @current_swipe.guest_couple_swipe_result = true
      @current_swipe.save
      # on check sil y a match
      check_match(@current_swipe)
      swipe_event_ids = Swipe.where(couple: current_couple, guest_couple_swipe: true).pluck(:event_id).uniq
      @events_for_display = Event.where.not(id: swipe_event_ids, couple: current_couple).where("date > ?", Date.today)
      if @current_swipe.match
        check_participation(@current_swipe)
      end
      format.json {
        render json: { current_swipe: @current_swipe, events: @events_for_display}
      }
    end
  end

  def guest_swipe_left
    set_swipe
    respond_to do  |format|
      @current_swipe = swipe_exists?(set_swipe)
      @current_swipe.guest_couple_swipe = true
      @current_swipe.guest_couple_swipe_result = false
      @current_swipe.save
      check_match(@current_swipe)
      swipe_event_ids = Swipe.where(couple: current_couple, guest_couple_swipe: true).pluck(:event_id).uniq
      @events_for_display = Event.where.not(id: swipe_event_ids, couple: current_couple).where("date > ?", Date.today)
      format.json {
        render json: { current_swipe: @current_swipe, events: @events_for_display}
      }
    end
  end

  def check_match(swipe)
    if (swipe.organizing_couple_swipe_result == true) && (swipe.guest_couple_swipe_result == true)
      swipe.match = true
      swipe.match_time =  Time.now
    else
      swipe.match = false
    end
    swipe.save
  end

  def check_participation(swipe)
    @current_nb_of_guests = swipe.event.swipes.where(participation: true).count
    if (swipe.event.max_n_guest_couples - @current_nb_of_guests) > 0
      swipe.participation = true
      swipe.notification_couple = true
      swipe.notification_event = true
      swipe.save
      # respond_to { |format| format.js} if swipe.participation
    end
  end

end

app/helpers/swipes_helper.rb
module SwipesHelper
end

app/views/swipes/_couple_deck.html.erb
<% couples_for_display.each do |couple| %>
  <div class="couple-card <%= couples_for_display.first == couple ? "active-card" : "hidden" %>" data-id="<%=couple.id%>" id="current-active-card">
    <div class="front couple-card-front">
      <div class="couple-description">
        <h2> <%= couple.member1_name.upcase %> & <%= couple.member2_name.upcase %></h2>
      </div>
      <div class="couple-picture">
        <%= cl_image_tag couple.profile_pict, width: 200, height: 150, crop: :fill %>
      </div>
      <div class="couple-badges">
        <%= image_tag 'fraise_rose_navbar.png', size: '20' %> <%= couple.fraises %>
      </div>
      <div class="couple-front-description">
        <%= couple.about_couple %>
      </div>

      <div class="couple-button-container">
        <%=link_to event_couple_swipeleft_path(@event, couple), method: :post, remote: true do %>
          <div class="swipe-btn organiser-swipe-left-btn"> <%= image_tag 'patate_blanche.png',  size: "40" %> </div>
        <% end %>
        <%= link_to event_couple_swiperight_path(@event, couple), method: :post, remote: true do %>
          <div class="swipe-btn organiser-swipe-right-btn"> <%= image_tag 'fraise-blanc-square.png', size: "50" %></div>
        <% end %>
      </div>
    </div>
    <div class="back event-card-back">
      <div class="back-couple-nickname">
      <%= couple.couple_nickname.upcase %>
      </div>
      <div class="back-couple-member-description">
        <%= couple.member1_name %>, <%= couple.age_member_1%> ans:  <br>
        <em>  "<%= couple.about_member1 %>" </em>
      </div>
      <div class="back-couple-member-description">
        <%= couple.member2_name %>, <%= couple.age_member_2%> ans:  <br>
        <em>  "<%= couple.about_member2 %>" </em>
      </div>
      <div class="link-to-organiser">
        <%= link_to couple_profile_path(couple), method: :get do%>
          Voir leur profil détaillé
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<div class="couple-card end-card <%= couples_for_display.length == 0 ? "active-card" : "hidden" %>" id="current-active-card">
  Plus de couples <br> dans votre zone, ramenez <br> votre fraise plus tard ...
  <%= image_tag 'fraise-blanc-square.png', size: "100" %>
</div>

app/views/swipes/_event_deck.html.erb
<% events_for_display.each do |event| %>
  <div class="event-card <%= events_for_display.first == event ? "active-card" : "hidden" %>" data-id="<%=event.id%>" id="current-active-card">
    <div class="front event-card-front">
      <div class="event-date"> <%= event.date %></div>
      <div class="event-description"> <h3> <%=event.theme.name.upcase %></h2>
        <p>chez</p>

          <h2> <%= event.couple.member1_name.upcase %> & <%= event.couple.member2_name.upcase %></h2>
      </div>
      <div class="organiser-picture">
        <%= cl_image_tag event.couple.profile_pict, width: 200, height: 150, crop: :fill %>

      </div>
      <div class="button-container">
        <%=link_to couple_event_swipeleft_path(current_couple, event), method: :post, remote: true do %>
          <div class="swipe-btn couple-swipe-left-btn"> <%= image_tag 'patate_blanche.png',  size: "40" %> </div>
        <% end %>
        <%= link_to couple_event_swiperight_path(current_couple, event), method: :post, remote: true do %>
          <div class="swipe-btn couple-swipe-right-btn"> <%= image_tag 'fraise-blanc-square.png', size: "50" %></div>
        <% end %>
      </div>
    </div>
    <div class="back event-card-back">
      <div class="back-event-title">
      <%=event.theme.name.upcase %>
      </div>
      <div class="back-event-description">
        <em>  "<%= event.description %>" </em>
      </div>
      <div class="back-no-guests">
        Nombre maximum de couples invités: <strong> <%=event.max_n_guest_couples %> </strong>
      </div>
      A propos des organisateurs:
      <div class="organiser-1">
        <%= event.couple.member1_name.capitalize %>: <br><em> "<%= event.couple.about_member1 %>" </em>
      </div>
      <div class="organiser-2">
        <%= event.couple.member2_name.capitalize %>: <br><em> "<%= event.couple.about_member2 %>"  </em>
      </div>
      <div class="organiser-badges">
        <%= image_tag 'fraise_rose_navbar.png', size: '20' %> <%= event.couple.fraises %>
      </div>
      <div class="link-to-organiser">
        <%= link_to couple_profile_path(event.couple), method: :get do%>
          Voir leur profil détaillé
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<div class="event-card end-card <%= events_for_display.length == 0 ? "active-card" : "hidden" %>" id="current-active-card">
  Plus d'évènements <br> dans votre zone, ramenez <br> votre fraise plus tard, <br> ou organisez votre <br> <%= link_to "propre évènement", new_organiser_event_path %>
  <%= image_tag 'fraise-blanc-square.png', size: "100" %>
</div>

app/views/swipes/_popup.html.erb
<p> It's a match !</p>

<p> Between <%= swipe.event.couple.member1_name%> and <%= swipe.event.couple.member2_name%></p>

app/views/swipes/guest_swipe_left.js.erb
$('#event-deck').html("<%= j render 'event_deck', events_for_display: @events_for_display %>")

app/views/swipes/guest_swipe_right.js.erb
$('#event-deck').html("<%= j render 'event_deck', events_for_display: @events_for_display %>")