config/routes.rb
Rails.application.routes.draw do
  devise_for :couples, controllers: { registrations: "registrations" }

  get 'couples/:id/edit-profile' => 'couples#edit', as: :my_profile
  patch  'couples/:id', to: 'couples#update'
  get    "couples/:id",      to: "couples#show", as: :couple_profile

  root to: 'pages#home'

  get 'challenges', to: 'pages#challenges'

    resources :couples do
        get 'my_events', to: 'events#my_events'
      resources :events do
        resources :swipes
        post 'swipeleft', to: 'swipes#guest_swipe_left'
        post 'swiperight', to: 'swipes#guest_swipe_right'
      end
    end

    resources :events do
      resources :couples do
        post 'swipeleft', to: 'swipes#organiser_swipe_left'
        post 'swiperight', to: 'swipes#organiser_swipe_right'
      end
    end

  namespace :organiser do
    resources :events do
      resources :couples
    end
  end

  resources :messages, only: [:new, :create, :destroy]

  resources :events do
    patch :notification_false
  end

  mount Attachinary::Engine => "/attachinary"

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :couple
  belongs_to :theme
  has_many :swipes
  has_many :messages

  after_create :add_master_badge



  def add_master_badge
    if couple.events.count == 5
      couple.badges << Badge.find_by(name: "Maitresse de Maison")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    available_event_list
  end

  def my_events
    @my_events = Event.where(couple: current_couple).order(date: :desc)
    @participating_events = Event.joins(:swipes).where(swipes: { couple_id: current_couple.id, participation: true })
    @swipes_true = Swipe.where(event_id: params[:id], participation: true)
  end

  def notification_false
    the_event = Event.find_by(id: params[:event_id])
    if current_couple == the_event.couple
      swipes_true = Swipe.where(event_id: the_event, participation: true)
      swipes_true.each do |st|
        st.notification_event = false
        st.save
      end
    else
      swipe_participating_couple = Swipe.where(event_id: the_event, couple_id: current_couple, participation: true).first
      swipe_participating_couple.notification_couple = false
      swipe_participating_couple.save
    end

    redirect_to event_path(the_event)
  end

  def new
    @event = current_couple.events.new
  end

  def create
    @event = current_couple.events.new(event_params)
    if @event.save
       current_couple.fraises += 3
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
  end

  def show
    @event = Event.find_by(id: params[:id])
    @message = Message.new()
    @swipes_true = Swipe.where(event_id: params[:id], participation: true)
  end


  def available_event_list
    swipe_event_ids = Swipe.where(couple: current_couple, guest_couple_swipe: true).pluck(:event_id).uniq
    @events_for_display = Event.where.not(id: swipe_event_ids, couple: current_couple).where("date > ?", Date.today)
 end




end

app/controllers/organiser/couples_controller.rb
class Organiser::CouplesController < ApplicationController

before_action :set_event

  def index
    available_couples_list

  end



  def set_event
    @event = Event.find(params[:event_id])
  end


  def available_couples_list
    swipe_couple_ids = Swipe.where(event: @event, organizing_couple_swipe: true).pluck(:couple_id)
    @couples_for_display = Couple.where.not(id: swipe_couple_ids).where.not(id: current_couple.id)
  end


end

app/controllers/organiser/events_controller.rb
class Organiser::EventsController < ApplicationController


  def index
    @events = current_couple.events

  end

  def new
    @event = current_couple.events.new
  end

  def edit
    @event =current_couple.events.find(params[:id])
  end

  def show
    @event =current_couple.events.find(params[:id])
  end

  def create
    @event = current_couple.events.new(event_params)
    if @event.save
      current_couple.fraises += 5
      current_couple.save
      redirect_to couple_event_path(current_couple, @event)
    else
      render 'new'
    end
  end

  def destroy
    @event = current_couple.events.find(params[:id])
    @event.destroy
    redirect_to organiser_events_path
  end


  def update
    @event = current_couple.events.find(params[:id])

    if @event.update(event_params)
      flash[:notice] = 'Your event was updated succesfully'
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end

  private

  def event_params
    params.require(:event).permit(:date, :description, :city,:max_n_guest_couples,:theme_id)
  end


end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/organiser/events/edit.html.erb
<div class="container">
   <div class="row">
     <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for([:organiser, @event]) do |f| %>
        <%= f.input :date, label: "Souhaitez-vous changer la date de votre evenement ?" %>
        <%= f.input :max_n_guest_couples, label: "Souhaitez vous changer le nombre de couples participants?" %>
        <%= f.input :description, label: "Souhaitez vous modifier le detail de votre evenement" %>
        <%= f.input :city, label: "Souhaitez vous changer le lieu de votre evenement ?" %>
        <%= f.button :submit %>
      <% end %>
   </div>
  </div>
</div

app/views/organiser/events/index.html.erb
<div class="container">
   <div class="row">
     <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <% @events.each do |event| %>
        <p>Date: <%= event.date %></p>
        <p>Lieu: <%= event.city %></p>
        <p>Description:  <%= event.description %> </p>
        <%= link_to("Supprimer", organiser_event_path(event), method: :delete) %>
        <%= link_to("Choix des participants", organiser_event_couples_path(event)) %>
        <%= link_to("Detail de l'evenement") %>
        <%= link_to("Editer votre evenement", edit_organiser_event_path(@event)) %>
      <% end %>

      </div>
  </div>
</div>

app/views/organiser/events/new.html.erb
<div class="background-form">

  <div class="container-fluid">

    <div id="title-de-retour">
      <h3 class="form-title-h3 title-event-padded">CE SOIR, C'EST LE GRAND SOIR !</h3>
    </div>

    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <div class="form-group form-inputs form-text">

          <%= simple_form_for([:organiser, @event]) do |f| %>
          <%= label_tag "", "QUEL THEME OSEREZ-VOUS CHOISIR ?" %>
            <div class="col-xs-12">
              <% Theme.all.each do |theme| %>
              <div class="col-xs-4">
                <div class="theme-group text-center">
                  <%= label_tag '', nil, class: 'small_label unfocus' do %>
                     <%= radio_button_tag("event[theme_id]", theme.id, checked = false, options = {class: "hide_radio"})%>
                      <%= image_tag theme.image_path, class: "picto"%>
                      <br>
                      <%= theme.name %>
                  <% end -%>
                </div>
              </div>
              <% end -%>
            </div>
            <%= f.input :max_n_guest_couples, label: "NOMBRE SOUHAITÉ DE COUPLES PARTICIPANTS ?", placeholder: 'Quel est le maximum :) ?', input_html: {:class => "form-inputs-background"} %>
            <%= f.input :description, :as => :text, label: "QUELQUES DÉTAILS SUR VOTRE FRAISE PARTIE !", placeholder: 'Récemment débarqués dans le coin, on se disait qu\'il serait de faire connaissance avec d\'autres couples autour d\'un petit brunch dimanche matin sur les bords de Loire. Avec 2 à 3 couples, chacun ramène quelque chose à manger et pourquoi ne pas passer l\'après-midi ensemble après si l\'envie nous prend !', input_html: {:class => "form-inputs-background"} %>
            <%= f.input :city, label: "OÙ AURA LIEU L'ÉVÉNEMENT ?", placeholder: 'Nantes', input_html: {:class => "form-inputs-background"} %>
            <%= f.input :date, label: "C'EST PRÉVU POUR BIENTÔT ?", input_html: {:class => "form-inputs-background input-unmarged"} %>
            <%= submit_tag("C'EST PARTI !", class: "form-submit-btn btn-unmarged") %>
          <% end %>

      </div>
    </div>
  </div>
</div>

<% content_for(:after_js) do %>
  <script type="text/javascript">
    $("#random_button").click(function(event) {
      event.preventDefault();
      $("#event_theme_id").val(randomValueFromSelect("#event_theme_id"));
    });

    var executed = false;
    $('.form-submit-btn').hover(function(event) {
        if (executed == false) {
        swal({
          title: "Allez-y, c'est permis !",
          text: "En créant cet événement, vous pouvez gagner 5 fraises supplémentaires",
          imageUrl: "<%= asset_path("plus5fraises.png")%>",
          imageSize: "200x120",
          confirmButtonText: "Compris !",
          confirmButtonColor: "#F80C54",
        });
        executed = true;
      }
    });

    $(".picto").on("click", function(){
      $(this).closest(".small_label").toggleClass("unfocus");
      $(".small_label").not(this.closest(".small_label")).addClass("unfocus");
    })

  </script>
<% end %>

app/views/organiser/events/show.html.erb
<h1>Evenement</h1>
<div class="container">
   <div class="row">
     <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <p>Date: <%= @event.date %></p>
        <p>Lieu <%= @event.city%></p>
        <p>Description <%= @event.description %> </p>
        <p>Theme <%= @event.theme.name %> </p>
        <%= link_to("Supprimer", organiser_event_path(@event), method: :delete) %>
        <%= link_to("Choix des participants", organiser_event_couples_path(@event)) %>
        <%= link_to("Detail de l'evenement") %>
        <%= link_to("Editer votre evenement", edit_organiser_event_path(@event)) %>

      </div>
  </div>
</div>